os: [ linux ]
dist: xenial
sudo: enabled
language: c

# Install mos tool
addons:
  apt:
    sources:
      - sourceline: "ppa:mongoose-os/mos"
    packages:
      - mos

script:
  - cd alien/build
  - ./build_all_local.sh
